#api call for listing all employee detials
###
GET http://127.0.0.1:8000/detials/
Accept: application/json


#api call for adding detials
###
POST http://127.0.0.1:8000/detials/
Content-Type: application/json

{
    "name":"anjana",

    "department" : "software tester",

    "salary" :30000,

    "location":"kochi",

    "age": 25,

    "experience":2

}

#api call for retrieve on data
###
GET http://127.0.0.1:8000/detials/2/
Accept: application/json

#api call for delete
###
DELETE http://127.0.0.1:8000/detials/2/

#api call for update
###
PUT http://127.0.0.1:8000/detials/1/

{
    "department":"quality tester"
}



